### ISSUE TITLE
Error Module

### ISSUE THREAD

**Issue by marcosliell** [bpextensions/mod_bppopup#6]
I'm using Joomla 3x, Php 7.3

When i open the module editor, show this:

Parse error: syntax error, unexpected '?' in /home/****/public_html/modules/mod_bppopup/fields/bpdonate.php on line 82

**Comment by artur-stepien** [comment]
Hi. Are you sure that this is PHP 7.3? The ?? operator was introduced in PHP 7.0
Can you copy the content of System/System Information/Download as text ?

**Comment by marcosliell** [comment]
Sorry, my php versão was 5.6, i change to 7.3 and works

**Comment by artur-stepien** [comment]
Happy I could help :)
